In [20]:
! pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2_binary-2.9.12-cp312-cp312-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.8/2.8 MB 2.6 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.8 MB 2.4 MB/s eta 0:00:01
   -------------------------- ------------- 1.8/2.8 MB 2.5 MB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 2.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

In [2]:
sheet_id="16qEUKckLFy7j1qoSd1bSQURn9QXDb6ffSBAWzRkPsSg"
sheet_name="Sheet1"


url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

traffic_df=pd.read_csv(url)

C:\Users\mcsub\AppData\Local\Temp\ipykernel_17364\1354536196.py:7: DtypeWarning: Columns (0: search_type) have mixed types. Specify dtype option on import or set low_memory=False.
  traffic_df=pd.read_csv(url)

In [ ]:
traffic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  str
 1   stop_time           65538 non-null  str
 2   country_name        65538 non-null  str
 3   driver_gender       65538 non-null  str
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  str
 7   violation_raw       65538 non-null  str
 8   violation           65538 non-null  str
 9   search_conducted    65538 non-null  bool
 10  search_type         43818 non-null  str
 11  stop_outcome        65538 non-null  str
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  str
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  str
dtypes: bool(3), int64(2), str(11)
memory usage: 6.7 MB

In [ ]:
traffic_df.describe()

       driver_age_raw   driver_age
count    65538.000000  65538.00000
mean        49.055998     49.11221
std         18.174699     18.15012
min         18.000000     18.00000
25%         33.000000     34.00000
50%         49.000000     49.00000
75%         65.000000     65.00000
max         80.000000     80.00000

In [ ]:
traffic_df.describe(include='object')

C:\Users\mcsub\AppData\Local\Temp\ipykernel_8976\3437929082.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  traffic_df.describe(include='object')

,stop_date,stop_time,country_name,driver_gender,driver_race,violation_raw,violation,search_type,stop_outcome,stop_duration,vehicle_number
count,65538,65538,65538,65538,65538,65538,65538,43818,65538,65538,65538
unique,46,1440,3,2,5,5,5,2,3,3,65538
top,2020-01-01,0:00:00,India,F,White,Seatbelt,Other,Frisk,Warning,30+ Min,UP76DY3473
freq,1440,46,21998,32881,13168,13204,13194,21971,21966,21958,1

In [ ]:
traffic_df.isnull().sum()

stop_date                 0
stop_time                 0
country_name              0
driver_gender             0
driver_age_raw            0
driver_age                0
driver_race               0
violation_raw             0
violation                 0
search_conducted          0
search_type           21720
stop_outcome              0
is_arrested               0
stop_duration             0
drugs_related_stop        0
vehicle_number            0
dtype: int64

In [3]:
db_url="postgresql://bose2831:hCEf5ple3AqCgEnyn9qi8X8mzsKeyJt5@dpg-d9jh5jjtqb8s73aces90-a.singapore-postgres.render.com/traffic"

In [4]:
from sqlalchemy import create_engine , inspect
engine = create_engine(db_url)

In [5]:
traffic_df.to_sql("traffic_stops",engine,index=False,if_exists="replace")

538

In [10]:
# 🚗 Vehicle-Based
#   1.What are the top 10 vehicle_Number involved in drug-related stops?

qurey="select vehicle_number,drugs_related_stop	from traffic_stops " \
        "where drugs_related_stop = True " \
        "order by drugs_related_stop DESC limit 10 "

drugs_related_vehicle=pd.read_sql(qurey,engine)
drugs_related_vehicle

  vehicle_number  drugs_related_stop
0     RJ83PZ4441                True
1     RJ32OM7264                True
2     RJ76TI3807                True
3     DL75KZ7835                True
4     DL50PO5101                True
5     UP67CQ9426                True
6     KA61JB1004                True
7     WB70IV9884                True
8     WB75TF1052                True
9     UP76DY3473                True

In [ ]:
#2.Which vehicles were most frequently searched?

qurey1="select vehicle_number,count(search_conducted) from traffic_stops " \
        "group by vehicle_number "

most_stfrequently_searched=pd.read_sql(qurey1,engine)
most_stfrequently_searched

      vehicle_number  count
0         TN44SG5218      1
1         WB99VD8787      1
2         MH62TJ7951      1
3         GJ82RI7659      1
4         KA88LB4605      1
...              ...    ...
65533     UP53ZO5356      1
65534     RJ39NG1606      1
65535     RJ59DO6246      1
65536     GJ62QG5587      1
65537     WB16BO6015      1

[65538 rows x 2 columns]

In [ ]:
# 🧍 Demographic-Based
# 3.Which driver age group had the highest arrest rate?

qurey2="select driver_age,count(is_arrested) as most_arrested from traffic_stops " \
        "group by driver_age " \
        "order by count(is_arrested) DESC"

highest_arrest_rate=pd.read_sql(qurey2,engine)
highest_arrest_rate

    driver_age  most_arrested
0           28           1100
1           38           1095
2           44           1095
3           41           1089
4           60           1081
..         ...            ...
58          67            998
59          23            995
60          42            994
61          24            969
62          20            967

[63 rows x 2 columns]

In [ ]:
# 4.What is the gender distribution of drivers stopped in each country?

qurey3="select driver_gender,stop_outcome,country_name,count(country_name) from traffic_stops " \
        "group by driver_gender,stop_outcome,country_name " \
        "order by country_name ASC"

gender_distribution=pd.read_sql(qurey3,engine)
gender_distribution

   driver_gender stop_outcome country_name  count
0              F      Warning       Canada   3734
1              M      Warning       Canada   3642
2              M       Ticket       Canada   3654
3              F       Arrest       Canada   3616
4              F       Ticket       Canada   3647
5              M       Arrest       Canada   3615
6              F       Arrest        India   3649
7              M       Ticket        India   3636
8              M       Arrest        India   3676
9              F      Warning        India   3695
10             M      Warning        India   3643
11             F       Ticket        India   3699
12             F       Arrest          USA   3604
13             F       Ticket          USA   3580
14             M       Arrest          USA   3574
15             F      Warning          USA   3657
16             M       Ticket          USA   3622
17             M      Warning          USA   3595

In [ ]:
# 5.Which race and gender combination has the highest search rate?

qurey4="select driver_gender,driver_race,search_type,count(search_type) from traffic_stops " \
        "group by driver_gender,driver_race,search_type " \
        "order by driver_race,driver_gender,search_type ASC"

highest_search_rate=pd.read_sql(qurey4,engine)
highest_search_rate

   driver_gender driver_race     search_type  count
0              F       Asian           Frisk   2278
1              F       Asian  Vehicle Search   2174
2              F       Asian             NaN      0
3              M       Asian           Frisk   2147
4              M       Asian  Vehicle Search   2173
5              M       Asian             NaN      0
6              F       Black           Frisk   2194
7              F       Black  Vehicle Search   2208
8              F       Black             NaN      0
9              M       Black           Frisk   2235
10             M       Black  Vehicle Search   2152
11             M       Black             NaN      0
12             F    Hispanic           Frisk   2153
13             F    Hispanic  Vehicle Search   2223
14             F    Hispanic             NaN      0
15             M    Hispanic           Frisk   2172
16             M    Hispanic  Vehicle Search   2176
17             M    Hispanic             NaN      0
18             F       Other           Frisk   2184
19             F       Other  Vehicle Search   2184
20             F       Other             NaN      0
21             M       Other           Frisk   2226
22             M       Other  Vehicle Search   2213
23             M       Other             NaN      0
24             F       White           Frisk   2257
25             F       White  Vehicle Search   2170
26             F       White             NaN      0
27             M       White           Frisk   2125
28             M       White  Vehicle Search   2174
29             M       White             NaN      0

In [ ]:
# 🕒 Time & Duration Based
# 6.What time of day sees the most traffic stops?

In [48]:
traffic_df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924