In [1]:
import pandas as pd

In [2]:
sheet_id="16qEUKckLFy7j1qoSd1bSQURn9QXDb6ffSBAWzRkPsSg"
sheet_name="Sheet1"


url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

traffic_df=pd.read_csv(url)

C:\Users\mcsub\AppData\Local\Temp\ipykernel_12568\1354536196.py:7: DtypeWarning: Columns (0: search_type) have mixed types. Specify dtype option on import or set low_memory=False.
  traffic_df=pd.read_csv(url)

In [3]:
db_url="postgresql://bose2831:hCEf5ple3AqCgEnyn9qi8X8mzsKeyJt5@dpg-d9jh5jjtqb8s73aces90-a.singapore-postgres.render.com/traffic"

In [4]:
from sqlalchemy import create_engine , inspect
engine = create_engine(db_url)

In [5]:
traffic_df.to_sql("traffic_stops",engine,index=False,if_exists="replace")

538

In [ ]:
# 🚗 Vehicle-Based
#   1.What are the top 10 vehicle_Number involved in drug-related stops?

query="select vehicle_number,drugs_related_stop	from traffic_stops " \
        "where drugs_related_stop = True " \
        "order by drugs_related_stop DESC limit 10 "

drugs_related_vehicle=pd.read_sql(query,engine)
drugs_related_vehicle

  vehicle_number  drugs_related_stop
0     RJ83PZ4441                True
1     RJ32OM7264                True
2     RJ76TI3807                True
3     DL75KZ7835                True
4     DL50PO5101                True
5     UP67CQ9426                True
6     KA61JB1004                True
7     WB70IV9884                True
8     WB75TF1052                True
9     UP76DY3473                True

In [ ]:
#2.Which vehicles were most frequently searched?

query1="select vehicle_number,count(*) as search_count from traffic_stops " \
        "where search_conducted = True " \
        "group by vehicle_number "

most_stfrequently_searched=pd.read_sql(query1,engine)
most_stfrequently_searched

      vehicle_number  search_count
0         TN72BR3512             1
1         TN24KB4148             1
2         TN16EN4769             1
3         MH85NR6252             1
4         KA36NX6664             1
...              ...           ...
32696     GJ96EH9266             1
32697     UP26VM5203             1
32698     TN44SG5218             1
32699     MH62TJ7951             1
32700     GJ82RI7659             1

[32701 rows x 2 columns]

In [ ]:
# 🧍 Demographic-Based
# 3.Which driver age group had the highest arrest rate?

query2="select driver_age,count(*) as most_arrested from traffic_stops " \
        "where is_arrested = True " \
        "group by driver_age " \
        "order by count(*) DESC"

highest_arrest_rate=pd.read_sql(query2,engine)
highest_arrest_rate

    driver_age  most_arrested
0           28            580
1           26            555
2           34            554
3           60            553
4           62            550
..         ...            ...
58          33            489
59          24            482
60          20            481
61          36            475
62          42            471

[63 rows x 2 columns]

In [ ]:
# 4.What is the gender distribution of drivers stopped in each country?

query3="select driver_gender,stop_outcome,country_name,count(country_name) from traffic_stops " \
        "group by driver_gender,stop_outcome,country_name " \
        "order by country_name ASC"

gender_distribution=pd.read_sql(query3,engine)
gender_distribution

   driver_gender stop_outcome country_name  count
0              F      Warning       Canada   3734
1              M      Warning       Canada   3642
2              M       Ticket       Canada   3654
3              F       Arrest       Canada   3616
4              F       Ticket       Canada   3647
5              M       Arrest       Canada   3615
6              F       Arrest        India   3649
7              M       Ticket        India   3636
8              M       Arrest        India   3676
9              F      Warning        India   3695
10             M      Warning        India   3643
11             F       Ticket        India   3699
12             F       Arrest          USA   3604
13             F       Ticket          USA   3580
14             M       Arrest          USA   3574
15             F      Warning          USA   3657
16             M       Ticket          USA   3622
17             M      Warning          USA   3595

In [ ]:
# 5.Which race and gender combination has the highest search rate?

query4="select driver_gender,driver_race,search_type,count(search_type) from traffic_stops " \
        "group by driver_gender,driver_race,search_type " \
        "order by driver_race,driver_gender,search_type ASC"

highest_search_rate=pd.read_sql(query4,engine)
highest_search_rate

   driver_gender driver_race     search_type  count
0              F       Asian           Frisk   2278
1              F       Asian  Vehicle Search   2174
2              F       Asian             NaN      0
3              M       Asian           Frisk   2147
4              M       Asian  Vehicle Search   2173
5              M       Asian             NaN      0
6              F       Black           Frisk   2194
7              F       Black  Vehicle Search   2208
8              F       Black             NaN      0
9              M       Black           Frisk   2235
10             M       Black  Vehicle Search   2152
11             M       Black             NaN      0
12             F    Hispanic           Frisk   2153
13             F    Hispanic  Vehicle Search   2223
14             F    Hispanic             NaN      0
15             M    Hispanic           Frisk   2172
16             M    Hispanic  Vehicle Search   2176
17             M    Hispanic             NaN      0
18             F       Other           Frisk   2184
19             F       Other  Vehicle Search   2184
20             F       Other             NaN      0
21             M       Other           Frisk   2226
22             M       Other  Vehicle Search   2213
23             M       Other             NaN      0
24             F       White           Frisk   2257
25             F       White  Vehicle Search   2170
26             F       White             NaN      0
27             M       White           Frisk   2125
28             M       White  Vehicle Search   2174
29             M       White             NaN      0

In [22]:
# 🕒 Time & Duration Based
# 6.What time of day sees the most traffic stops?

query5="SELECT " \
            "EXTRACT(HOUR FROM stop_time::time) AS hour," \
            "COUNT(*) AS total_stops " \
        "FROM traffic_stops " \
        "GROUP BY hour " \
        "ORDER BY total_stops DESC;"

most_traffic_stops=pd.read_sql(query5,engine)
most_traffic_stops

    hour  total_stops
0    5.0         2760
1    0.0         2760
2    2.0         2760
3    9.0         2760
4    3.0         2760
5    7.0         2760
6   11.0         2760
7    4.0         2760
8    6.0         2760
9   10.0         2760
10   1.0         2760
11   8.0         2760
12  12.0         2718
13  19.0         2700
14  17.0         2700
15  16.0         2700
16  14.0         2700
17  23.0         2700
18  18.0         2700
19  22.0         2700
20  21.0         2700
21  13.0         2700
22  20.0         2700
23  15.0         2700

In [ ]:
# 7.What is the average stop duration for different violations?

query6="SELECT violation, " \
        "AVG(" \
        "   CASE " \
                "WHEN stop_duration = '0-15 Min' THEN 7.5 " \
                "WHEN stop_duration = '16-30 Min' THEN 23 " \
                "WHEN stop_duration = '30+ Min' THEN 35 " \
            "END" \
        ") AS avg_stop_minutes " \
        "FROM traffic_stops " \
        "GROUP BY violation " \
        "ORDER BY avg_stop_minutes DESC;"

avg_stop_duration=pd.read_sql(query6,engine)
avg_stop_duration

  violation  avg_stop_minutes
0     Other         22.203312
1  Seatbelt         21.833205
2  Speeding         21.794487
3       DUI         21.741338
4    Signal         21.712096

In [ ]:
# 8.Are stops during the night more likely to lead to arrests?

query7="SELECT " \
            "CASE " \
                "WHEN EXTRACT(HOUR FROM stop_time::time) >= 18 OR EXTRACT(HOUR FROM stop_time::time) < 6 " \
                "THEN 'Night' " \
                "ELSE 'Day' " \
                "END AS time_period, " \
                "COUNT(*) AS total_stops," \
                "SUM(CASE WHEN is_arrested = TRUE THEN 1 ELSE 0 END) AS arrests," \
                "ROUND(100.0 * SUM(CASE WHEN is_arrested = TRUE THEN 1 ELSE 0 END) / COUNT(*),2) AS arrest_rate " \
        "FROM traffic_stops " \
        "GROUP BY time_period " \
        "ORDER BY arrest_rate DESC;"


arrest_rate=pd.read_sql(query7,engine)
arrest_rate

  time_period  total_stops  arrests  arrest_rate
0         Day        32778    16557        50.51
1       Night        32760    16289        49.72

In [24]:
# ⚖️ Violation-Based
# 9.Which violations are most associated with searches or arrests?

query8="select violation,COUNT(*) AS searches_or_arrests from traffic_stops " \
"where search_conducted = True OR is_arrested = True " \
"group by violation " \
"order by searches_or_arrests DESC ;"


searches_or_arrests=pd.read_sql(query8,engine)
searches_or_arrests

  violation  searches_or_arrests
0  Speeding                 9868
1       DUI                 9867
2     Other                 9857
3  Seatbelt                 9774
4    Signal                 9773

In [28]:
# 10.Which violations are most common among younger drivers (<25)?

query9="select violation,COUNT(*) AS Driver_age_below25 from traffic_stops " \
"where driver_age < 25 " \
"group by violation " \
"order by Driver_age_below25 DESC"

Driver_age_below25=pd.read_sql(query9,engine)
Driver_age_below25

  violation  driver_age_below25
0  Speeding                1476
1    Signal                1427
2     Other                1422
3  Seatbelt                1420
4       DUI                1359

In [ ]:
# 11.Is there a violation that rarely results in search or arrest?

query10="SELECT violation,COUNT(*) AS total_stops, " \
            "SUM(CASE WHEN search_conducted = TRUE OR is_arrested = TRUE THEN 1 ELSE 0 END) AS searches_or_arrests," \
            "ROUND(100.0 * SUM(CASE WHEN search_conducted = TRUE OR is_arrested = TRUE THEN 1 ELSE 0 END)" \
            " / COUNT(*),2) AS search_arrest_rate " \
        "FROM traffic_stops " \
        "GROUP BY violation " \
        "ORDER BY search_arrest_rate ASC;"

search_arrest_rate=pd.read_sql(query10,engine)
search_arrest_rate

  violation  total_stops  searches_or_arrests  search_arrest_rate
0    Signal        13112                 9773               74.53
1     Other        13194                 9857               74.71
2  Speeding        13150                 9868               75.04
3  Seatbelt        13007                 9774               75.14
4       DUI        13075                 9867               75.46

In [ ]:
# 🌍 Location-Based
# 12.Which countries report the highest rate of drug-related stops?

query11="select country_name," \
            "ROUND(100.0 * SUM(CASE WHEN drugs_related_stop = TRUE THEN 1 ELSE 0 END) / COUNT(*),2) as rate_of_drug_related_stops " \
        "from traffic_stops " \
        "group by country_name;"

rate_of_drug_related_stops=pd.read_sql(query11,engine)
rate_of_drug_related_stops

  country_name  rate_of_drug_related_stops
0       Canada                       50.10
1        India                       49.54
2          USA                       50.37

In [35]:
#13.What is the arrest rate by country and violation?

query12="select violation,country_name," \
            "ROUND(100.0 * SUM(CASE WHEN is_arrested = TRUE THEN 1 ELSE 0 END) / COUNT(*),2) as arrest_rate " \
        "from traffic_stops " \
        "group by country_name,violation " \
        "order by country_name DESC;"

arrest_rate_by_country_and_violation=pd.read_sql(query12,engine)
arrest_rate_by_country_and_violation

   violation country_name  arrest_rate
0        DUI          USA        49.66
1      Other          USA        48.59
2     Signal          USA        49.99
3   Speeding          USA        49.83
4   Seatbelt          USA        50.58
5   Speeding        India        50.76
6   Seatbelt        India        50.56
7     Signal        India        50.65
8        DUI        India        50.84
9      Other        India        49.29
10  Speeding       Canada        49.94
11  Seatbelt       Canada        50.46
12    Signal       Canada        49.18
13     Other       Canada        50.29
14       DUI       Canada        51.13

In [37]:
# 14.Which country has the most stops with search conducted
query13="select country_name,count(*) as search_count from traffic_stops " \
        "where search_conducted = True " \
        "group by country_name " \
        "order by search_count DESC " \
        "limit 1;"

search_count=pd.read_sql(query13,engine)
search_count

  country_name  search_count
0       Canada         11020

In [48]:
traffic_df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924